FROM node:22-alpine

WORKDIR /app

# Accept build arguments
ARG PORT
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG AWS_BUCKET
ARG COGNITO_USER_POOL_ID
ARG COGNITO_APP_CLIENT_ID
ARG CLOUDFRONT_DOMAIN
ARG MONGODB_URI

# Set environment variables
ENV PORT=$PORT
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_REGION=$AWS_REGION
ENV AWS_BUCKET=$AWS_BUCKET
ENV COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID
ENV COGNITO_APP_CLIENT_ID=$COGNITO_APP_CLIENT_ID
ENV CLOUDFRONT_DOMAIN=$CLOUDFRONT_DOMAIN
ENV MONGODB_URI=$MONGODB_URI

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
